import { ElementRef, Renderer, OnInit, AfterViewInit } from '@angular/core';
export declare class ClockPicker implements OnInit, AfterViewInit {
    elem: ElementRef;
    renderer: Renderer;
    hoursPlate: ElementRef;
    minutesPlate: ElementRef;
    plate: ElementRef;
    svg: ElementRef;
    g: ElementRef;
    hand: ElementRef;
    fg: ElementRef;
    bg: ElementRef;
    bearing: ElementRef;
    twelvehour: boolean;
    darktheme: boolean;
    placeholder: String;
    label: string;
    duration: number;
    showClock: boolean;
    showHours: boolean;
    dialRadius: number;
    outerRadius: number;
    innerRadius: number;
    tickRadius: number;
    diameter: number;
    hoursTicks: any;
    minutesTicks: any;
    selectedHours: any;
    endHours: string;
    touchSupported: any;
    mousedownEvent: any;
    mousemoveEvent: any;
    mouseupEvent: any;
    constructor(elem: ElementRef, renderer: Renderer);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    checkDraw(): void;
    mousedown(e: any, space: any): void;
    openBtnClicked(): void;
    closeBtnClicked(): void;
    setHour(hour: String): void;
    setMinute(min: String): void;
    setAmPm(ampm: String): void;
    showHoursClock(): void;
    showMinutesClock(): void;
    generateTick(): void;
    setHand(x: any, y: any, roundBy5: any, draging: any): void;
    offset(obj: any): {
        left: number;
        top: number;
    };
}
